import ProtectRoute from "@/components/ProtectRoute";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "page 1",
  description: "description page 1",
};

/* anther way to generate metadata (if we ge some thing from api) */
/* export async function generateMetadata({ params }) {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  };
} */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ProtectRoute user="user" />
      {children}
    </>
  );
}
